# Docker compose file for building images
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./backend:/backend
    networks:
      - app-network
    image: journey-wonder-backend:1.0.2

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - ./frontend:/frontend
    networks:
      - app-network
    depends_on:
      - backend
    image: journey-wonder-frontend:1.0.2

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
    image: journey-wonder:1.0.2

networks:
  app-network:
    driver: bridge