name: Docker Image CI

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger this workflow on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up Docker Buildx (optional but recommended for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/journey-wonder:1.0.1 .
        
      # Step 5: Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/journey-wonder:1.0.1
